version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: meu_postgres
    environment:
      POSTGRES_USER: yuri_toledo
      POSTGRES_PASSWORD: DockerPostgreSQL#
      POSTGRES_DB: montechDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
